---
title: u!magine
tagline: Innovate Incubate Educate
email: uimagine@csu.edu.au
description: uImagine is the Learning Innovations Lab at Charles Sturt University
baseurl: "/uimagine-website"
logo: assets/images/uimagine-rev.svg
url: https://uimagine.edu.au
encoding: utf-8
social-twitter: uimagine_csu
social-youtube: UCq0r8DVFLLK3YtFylr0KxtQ/videos
social-flickr: uimagine
contact-email: uimagine@csu.edu.au
contact-address: Boorooma Street, Wagga Wagga, Australia
contact-phone: 
contact-name: uImagine Team
include:
- _pages
permalink: "/:year/:title.html"
collections:
  events:
    output: true
    permalink: "/:collection/:name"
  projects:
    output: true
    permalink: "/:collection/:name"
  team:
    output: true
    permalink: "/:collection/:name"
timezone: Australia/Sydney
markdown: kramdown
kramdown:
  auto_ids: true
brand: FF5800
brand-1: 333333
brand-2: 00AFD8
brand-3: CB0044
brand-4: D71F85
Blue: 64142
Fucia: 203068
Grey: 515151
Orange: 255880
Pink: 21531133
font-link: https://fonts.googleapis.com/css?family=Open+Sans:300,400,700
google_maps_javascript_api_key: AIzaSyCokyUeWni-eQFPDP7IkCWNdi568wlQSTM
99inbound: U0zlygKF
og_image: uimagine-site-image.png
og_locale: en_AU
