---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url:
collections:
- path: _posts
  templates:
  - blog
  label: Blog
  create: all
- path: _events
  templates:
  - event
  label: Events
  create: all
- path: _projects
  templates:
  - project
  label: Projects
  create: all
- path: ''
  label: Pages
  create: all
- path: _team
  templates:
  - team-member
  label: Team
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
