---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url:
collections:
- path: _posts
  label: Blog
  create: all
  templates:
  - blog
- path: _events
  label: Events
  create: all
  templates:
  - event
- path: _projects
  label: Projects
  create: all
  templates:
  - project
- path: _pages
  label: Pages
  create: all
- path: _team
  label: Team
  create: all
  templates:
  - team-member
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
