---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-posts
  label: Blog
  create: all
  templates:
  - blog
- type: directory
  path: _events
  label: Events
  create: all
  match: "**/*"
  templates:
  - event
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
- type: directory
  path: _team
  label: Team
  create: all
  match: "**/*"
  templates:
  - team-member
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
