---
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: true
  default: project
  config:
    required: true
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- type: select
  name: categories
  config:
    source:
      type: simple
    options:
    - Innovation
    - Incubation
    - Open Education
    required: true
  label: Categories
  description: Chose the applicable program of work
  default: Innovation
- type: select
  name: status
  config:
    source:
      type: simple
    options:
    - ongoing
    - complete
    required: true
  label: Status
  default: ongoing
- type: number
  name: progress
  label: Progress
  config:
    min: '1'
    max: '100'
    step: '5'
    required: true
  default: ''
  description: percentage of project completed
- name: date-start
  label: Date start
  type: datetime
  hidden: false
  default: ''
  config:
    required: true
- name: date-finish
  label: Date finish
  type: datetime
  hidden: false
  default: ''
- name: summary
  label: Summary
  type: textarea
  hidden: false
  default: ''
  config:
    wysiwyg: false
    schema:
      format: markdown
    required: true
  description: Short summary of the projects aims
- name: team
  label: Team
  type: list
  hidden: false
  default: ''
  description: Team members involved in the project - just names (no titles)
- name: focus
  label: Focus
  type: list
  hidden: false
  default: ''
  config:
    use_select: true
    source:
      type: simple
    options:
    - resource
    - experience
    - pedagogy
    - practice
    - research
    - scholarship
    - new technology
    - course
    - strategic direction
  description: What output is this project focussed on producing?
- name: outputs
  label: Outputs
  type: field_group_list
  fields:
  - name: description
    label: Description
    type: text
    hidden: false
    default: ''
  - name: file
    label: File
    type: file
    hidden: false
    default: ''
    description: Upload relevant files here
  - type: text
    name: link
    label: Link
    description: For online output - paste link URL here
  hidden: false
  default: ''
  config:
    labelField: description
  description: Resources produced by the project - reports, document etc
- name: hero
  label: Hero
  type: field_group
  fields:
  - name: full_screen
    label: Full screen
    type: boolean
    hidden: false
    default: ''
  - name: gradient_corner
    label: Gradient corner
    type: text
    hidden: false
    default: ''
  - name: gradient_side
    label: Gradient side
    type: text
    hidden: false
    default: ''
  - name: gradient_color_1
    label: Gradient color 1
    type: text
    hidden: false
    default: '203,0,68'
  - name: gradient_color_2
    label: Gradient color 2
    type: text
    hidden: false
    default: '0,175,216'
  - name: image
    label: Image
    type: file
    hidden: false
    default: ''
  - name: icon
    label: Icon
    type: file
    hidden: false
    default: ''
  hidden: false
  default: ''
- type: field_group
  name: hero
  label: Hero
  description: Information for page banner
  fields:
  - type: select
    name: gradient_corner
    config:
      source:
        type: simple
      options:
      - top
      - bottom
    label: Gradient Corner
  - type: select
    config:
      source:
        type: simple
      options:
      - left
      - right
    label: Gradient side
    name: gradient_side
  - type: text
    name: gradient_color_1
    label: Gradient color 1
  - type: text
    name: gradient_color_2
    label: Gradient Color 2
  - type: file
    name: icon
    label: Icon
  - type: file
    name: image
    label: Image
pages:
- _projects/test.md
- _projects/csu-online-learning-model.md
- _projects/eexam-trials.md
- _projects/destination-2020.md
- _projects/blackboard-improve.md
