---
hide_body: false
is_partial: false
fields:
- name: layout
  label: Layout
  type: text
  hidden: true
  default: project
  config:
    required: true
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
  config:
    required: true
- type: select
  name: status
  config:
    source:
      type: simple
    options:
    - ongoing
    - complete
    required: true
  label: Status
  default: ongoing
- type: list
  label: Category
  name: category
  description: Select area of work
  config:
    use_select: true
    source:
      type: simple
    options:
    - incubation
    - innovation
    - open
- type: number
  name: progress
  label: Progress
  config:
    min: '1'
    max: '100'
    step: '5'
    required: true
  default: ''
  description: percentage of project completed
- name: date-start
  label: Date start
  type: datetime
  hidden: false
  default: ''
  config:
    required: true
- name: date-finish
  label: Date finish
  type: datetime
  hidden: false
  default: ''
- name: summary
  label: Summary
  type: textarea
  hidden: false
  default: ''
  config:
    wysiwyg: false
    schema:
      format: markdown
    required: true
  description: Short summary of the projects aims
- name: team
  label: Team
  type: list
  hidden: false
  default: ''
  description: Team members involved in the project - just names (no titles)
- name: focus
  label: Focus
  type: list
  hidden: false
  default: ''
  config:
    use_select: true
    source:
      type: simple
    options:
    - resource
    - experience
    - pedagogy
    - practice
    - research
    - scholarship
    - new technology
    - course
    - strategic direction
  description: What output is this project focussed on producing?
- name: outputs
  label: Outputs
  type: field_group_list
  fields:
  - name: description
    label: Link Text
    type: text
    hidden: false
    default: ''
    description: Text Description
  - name: file
    label: File
    type: file
    hidden: false
    default: ''
    description: Upload file or use media library
  - type: text
    name: link
    label: Link
    description: Or supply URL
  hidden: false
  default: ''
  config:
    labelField: description
  description: Resources produced by the project - reports, document etc
- type: field_group
  name: hero
  label: Hero
  description: Information for page banner
  fields:
  - type: select
    name: gradient_corner
    config:
      source:
        type: simple
      options:
      - top
      - bottom
    label: Gradient Corner
    default: top
  - type: select
    config:
      source:
        type: simple
      options:
      - left
      - right
    label: Gradient side
    name: gradient_side
  - type: text
    name: gradient_color_1
    label: Gradient color 1
    default: '203,0,68'
  - type: text
    name: gradient_color_2
    label: Gradient Color 2
    default: '0,175,216'
  - type: file
    name: icon
    label: Icon
  - type: file
    name: image
    label: Image
pages:
- _projects/online-learning-exchange.md
- _projects/ecotourism-taster.md
- _projects/zeetings-trial.md
- _projects/engagement-in-online-lectures.md
- _projects/biomedical-learning-resources.md
- _projects/de-transition-support.md
- _projects/blackboard-improve.md
- _projects/online-learning-model-scale-up.md
- _projects/online-learning-model-pilots.md
- _projects/quality-learning-teaching-initiative.md
- _projects/h5p-server.md
- _projects/destination-2020.md
- _projects/incubation-strategy.md
- _projects/eexam-trials.md
